version: "3.9"
services:
  mediahub:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - FLASK_RUN_PORT=5000
    ports: ["5000:5000"]
    volumes:
      - ./storage:/app/storage
      - ./downloads:/app/downloads
      - ./bin:/app/bin
